### ISSUE TITLE
Can you release x86 version?

### ISSUE THREAD

**Issue by Lessyzz** [ImAxel0/IL2CPP_Scanner_Reborn#3]
I need x86 version

**Comment by ImAxel0** [comment]
This is the compiled x86 version, however I don't know if it works. Anyway I suggest to use famous tools like [UnityExplorer](https://github.com/sinai-dev/UnityExplorer) which are far better.

[IL2CPP Scanner Reborn x86.zip](https://github.com/user-attachments/files/17968624/IL2CPP.Scanner.Reborn.x86.zip)

**Comment by Lessyzz** [comment]
> This is the compiled x86 version, however I don't know if it works. Anyway I suggest to use famous tools like [UnityExplorer](https://github.com/sinai-dev/UnityExplorer) which are far better.
> 
> [IL2CPP Scanner Reborn x86.zip](https://github.com/user-attachments/files/17968624/IL2CPP.Scanner.Reborn.x86.zip)

thanks for x86. I worked with UnityExplorer before but the game blocking melonloader as far as i know i can use ue with melonloader only so i choose this
